import { Engine } from "../src/index.js";
import { createPostgresStore } from "../src/pg-store.js";
const { registerWorkflow } = await import("../src/index.js");
const { parityWorkflow, registerAll } = await import("./workflow-def.js");
registerAll();
const store = await createPostgresStore(process.env.LIGHTFLOW_PG_URL);
const engine = new Engine(store, { pollMs: 300, staleRunMs: 15000 });
const runId = process.argv[2];
await engine.resume(runId);
const row = await store.getRun(runId);
console.log("FINAL", row?.status, JSON.stringify(row?.output));
process.exit(0);
